// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkAfwVcVbtP207Gl-nnzOvY0vG-FqHpiQ',
    appId: '1:403761172017:web:34d2a2e0547d77d01e4f10',
    messagingSenderId: '403761172017',
    projectId: 'kitchenly-271e8',
    authDomain: 'kitchenly-271e8.firebaseapp.com',
    storageBucket: 'kitchenly-271e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfOOJ2J0ijqOvPqY990-GNhrKHu_O28iA',
    appId: '1:403761172017:android:968f6224c46a87c11e4f10',
    messagingSenderId: '403761172017',
    projectId: 'kitchenly-271e8',
    storageBucket: 'kitchenly-271e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZN3IAXiH481cjTiaZWnQQtYw3YbngvbI',
    appId: '1:403761172017:ios:0fa512a3809002da1e4f10',
    messagingSenderId: '403761172017',
    projectId: 'kitchenly-271e8',
    storageBucket: 'kitchenly-271e8.firebasestorage.app',
    iosBundleId: 'com.example.kitchenly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZN3IAXiH481cjTiaZWnQQtYw3YbngvbI',
    appId: '1:403761172017:ios:0fa512a3809002da1e4f10',
    messagingSenderId: '403761172017',
    projectId: 'kitchenly-271e8',
    storageBucket: 'kitchenly-271e8.firebasestorage.app',
    iosBundleId: 'com.example.kitchenly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkAfwVcVbtP207Gl-nnzOvY0vG-FqHpiQ',
    appId: '1:403761172017:web:101eec7f2d3f05f01e4f10',
    messagingSenderId: '403761172017',
    projectId: 'kitchenly-271e8',
    authDomain: 'kitchenly-271e8.firebaseapp.com',
    storageBucket: 'kitchenly-271e8.firebasestorage.app',
  );
}
